import sqlite3
from typing import Optional
from database import get_connection


def row_to_dict(row: sqlite3.Row) -> dict:
    """
    Converts a sqlite3.Row into a plain Python dictionary.

    Also converts the integer `done` column (0 or 1) into a real
    Python boolean so JSON responses show true/false, not 1/0.
    """
    data = dict(row)
    data["done"] = bool(data["done"])
    return data


# ─────────────────────────────────────────
# READ
# ─────────────────────────────────────────

def db_get_all_tasks() -> list[dict]:
    """Returns every task in the database, ordered by id."""
    sql = "SELECT id, title, done, created_at, updated_at FROM tasks ORDER BY id ASC"
    conn = get_connection()
    try:
        rows = conn.execute(sql).fetchall()
    finally:
        conn.close()
    return [row_to_dict(r) for r in rows]


def db_get_task_by_id(task_id: int) -> Optional[dict]:
    """
    Returns a single task by primary key.
    Returns None if the id does not exist so the route can raise 404.
    """
    sql = "SELECT id, title, done, created_at, updated_at FROM tasks WHERE id = ?"
    conn = get_connection()
    try:
        row = conn.execute(sql, (task_id,)).fetchone()
    finally:
        conn.close()
    return row_to_dict(row) if row else None


# ─────────────────────────────────────────
# CREATE
# ─────────────────────────────────────────

def db_create_task(title: str, done: bool = False) -> dict:
    """
    Inserts a new row, then reads it back.

    We re-select after inserting because the id and the
    created_at / updated_at timestamps are generated by SQLite,
    not by Python.
    """
    insert_sql = "INSERT INTO tasks (title, done) VALUES (?, ?)"
    select_sql = "SELECT id, title, done, created_at, updated_at FROM tasks WHERE id = ?"

    conn = get_connection()
    try:
        cursor = conn.execute(insert_sql, (title, 1 if done else 0))
        conn.commit()
        new_id = cursor.lastrowid
        row = conn.execute(select_sql, (new_id,)).fetchone()
    finally:
        conn.close()
    return row_to_dict(row)


# ─────────────────────────────────────────
# UPDATE
# ─────────────────────────────────────────

def db_update_task(task_id: int, title: Optional[str], done: Optional[bool]) -> Optional[dict]:
    """
    Updates title and/or done on an existing row.

    Any field the client omits keeps its current value,
    so a partial update never wipes out existing data.
    """
    existing = db_get_task_by_id(task_id)
    if existing is None:
        return None

    final_title = title if title is not None else existing["title"]
    final_done = done if done is not None else existing["done"]

    update_sql = """
        UPDATE tasks
        SET title = ?, done = ?, updated_at = datetime('now')
        WHERE id = ?
    """
    select_sql = "SELECT id, title, done, created_at, updated_at FROM tasks WHERE id = ?"

    conn = get_connection()
    try:
        conn.execute(update_sql, (final_title, 1 if final_done else 0, task_id))
        conn.commit()
        row = conn.execute(select_sql, (task_id,)).fetchone()
    finally:
        conn.close()
    return row_to_dict(row)


# ─────────────────────────────────────────
# DELETE
# ─────────────────────────────────────────

def db_delete_task(task_id: int) -> bool:
    """
    Deletes a task by id.

    cursor.rowcount tells us how many rows the DELETE affected.
        rowcount > 0  -> the task existed and is now gone  -> True
        rowcount == 0 -> no such id                        -> False (route raises 404)
    """
    conn = get_connection()
    try:
        cursor = conn.execute("DELETE FROM tasks WHERE id = ?", (task_id,))
        conn.commit()
        return cursor.rowcount > 0
    finally:
        conn.close()